# Generated by Django 5.2.4 on 2025-07-05 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('artist', 'Artist'), ('user', 'User')], max_length=10),
        ),
    ]
