# Generated by Django 5.2.6 on 2025-09-27 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_artwork_category_artwork_dimensions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
