# Generated by Django 5.2.6 on 2025-09-27 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_membership_expiry_date_membership_plan_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membership',
            name='plan_type',
        ),
        migrations.RemoveField(
            model_name='membership',
            name='start_date',
        ),
        migrations.AlterField(
            model_name='membership',
            name='payment_status',
            field=models.CharField(default='pending', max_length=50),
        ),
    ]
