# Generated by Django 5.2.6 on 2025-09-27 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='stock',
            field=models.IntegerField(default=1),
        ),
    ]
