# Generated by Django 5.2.6 on 2025-09-28 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_passwordresettoken'),
        ('home', '0009_user_membership_amount_user_membership_expiry_date_and_more'),
    ]

    operations = [
    ]
